# Spring Configuration
spring:
  application:
    name: Wallet User Registry
# Server Configuration
server:
  port: 8085

# Logging Configuration
logging:
  level:
    es.in2.wallet.user.registry.api.service: DEBUG
    es.in2.wallet.user.registry.api.utils: DEBUG

# Actuator Configuration
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, loggers, metrics
      base-path: /
      path-mapping:
        health: health
        info: info
        loggers: loggers
        metrics: metrics
  endpoint:
    health:
      enabled: true
      show-details: always
    loggers:
      enabled: true
    metrics:
      enabled: true

# Documentation Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /spring-ui
    tags-sorter: alpha
    operations-sorter: method

keycloak:
  url: http://localhost:8084
  realm: WalletIdP
  client-secret: fV51P8jFBo8VnFKMMuP3imw3H3i5mNck
  client-id: wallet-client

wallet-data:
  url: http://localhost:8086

openapi:
  server:
    url: http://localhost:8085
    description: Spring Wallet User Registry API
  info:
    title: IN2 Wallet User Registry API project
    version: 0.0.1
    termsOfService: $apiUrl/terms-of-service
    license:
      name: MIT License
      url: https://choosealicense.com/licenses/mit/
    contact:
      email: example@in2.es
      name: IN2
      url: https://in2.es
    description: This API exposes endpoints to manage the IN2 Blockchain Connector component.
