# Spring Configuration
spring:
  application:
    name: Wallet User Registry

# Server Configuration
server:
  port: 8080

# Logging Configuration
logging:
  level:
    es.in2.walletuserregistry: DEBUG

# Actuator Configuration
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, loggers, metrics, prometheus
      base-path: /
      path-mapping:
        health: health
        info: info
        loggers: loggers
        metrics: metrics
        prometheus: prometheus
  endpoint:
    health:
      enabled: true
      show-details: always
    loggers:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true

# Documentation Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /spring-ui
    tags-sorter: alpha
    operations-sorter: method

keycloak:
  url:
  realm:
  client-secret:
  client-id:

wallet-data:
  url:

wallet-wda:
  url:

openapi:
  server:
    url:
    description:
  info:
    title:
    version:
    termsOfService:
    license:
      name:
      url:
    contact:
      email:
      name:
      url:
    description: